# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_create_deck.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogCreateDeck(object):
    def setupUi(self, DialogCreateDeck):
        DialogCreateDeck.setObjectName("DialogCreateDeck")
        DialogCreateDeck.resize(351, 418)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogCreateDeck)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.group_class = QtWidgets.QGroupBox(DialogCreateDeck)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.group_class.setFont(font)
        self.group_class.setObjectName("group_class")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.group_class)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioButton_Druid = QtWidgets.QRadioButton(self.group_class)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_Druid.setFont(font)
        self.radioButton_Druid.setChecked(True)
        self.radioButton_Druid.setObjectName("radioButton_Druid")
        self.gridLayout_2.addWidget(self.radioButton_Druid, 0, 0, 1, 1)
        self.radioButton_Hunter = QtWidgets.QRadioButton(self.group_class)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_Hunter.setFont(font)
        self.radioButton_Hunter.setObjectName("radioButton_Hunter")
        self.gridLayout_2.addWidget(self.radioButton_Hunter, 0, 1, 1, 1)
        self.radioButton_Mage = QtWidgets.QRadioButton(self.group_class)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_Mage.setFont(font)
        self.radioButton_Mage.setObjectName("radioButton_Mage")
        self.gridLayout_2.addWidget(self.radioButton_Mage, 0, 2, 1, 1)
        self.radioButton_Priest = QtWidgets.QRadioButton(self.group_class)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_Priest.setFont(font)
        self.radioButton_Priest.setObjectName("radioButton_Priest")
        self.gridLayout_2.addWidget(self.radioButton_Priest, 1, 0, 1, 1)
        self.radioButton_Shaman = QtWidgets.QRadioButton(self.group_class)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_Shaman.setFont(font)
        self.radioButton_Shaman.setObjectName("radioButton_Shaman")
        self.gridLayout_2.addWidget(self.radioButton_Shaman, 1, 1, 1, 1)
        self.radioButton_Rogue = QtWidgets.QRadioButton(self.group_class)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_Rogue.setFont(font)
        self.radioButton_Rogue.setObjectName("radioButton_Rogue")
        self.gridLayout_2.addWidget(self.radioButton_Rogue, 1, 2, 1, 1)
        self.radioButton_Paladin = QtWidgets.QRadioButton(self.group_class)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_Paladin.setFont(font)
        self.radioButton_Paladin.setObjectName("radioButton_Paladin")
        self.gridLayout_2.addWidget(self.radioButton_Paladin, 2, 0, 1, 1)
        self.radioButton_Warlock = QtWidgets.QRadioButton(self.group_class)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_Warlock.setFont(font)
        self.radioButton_Warlock.setObjectName("radioButton_Warlock")
        self.gridLayout_2.addWidget(self.radioButton_Warlock, 2, 1, 1, 1)
        self.radioButton_Warrior = QtWidgets.QRadioButton(self.group_class)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_Warrior.setFont(font)
        self.radioButton_Warrior.setObjectName("radioButton_Warrior")
        self.gridLayout_2.addWidget(self.radioButton_Warrior, 2, 2, 1, 1)
        self.radioButton_Monk = QtWidgets.QRadioButton(self.group_class)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_Monk.setFont(font)
        self.radioButton_Monk.setObjectName("radioButton_Monk")
        self.gridLayout_2.addWidget(self.radioButton_Monk, 3, 0, 1, 1)
        self.radioButton_DeathKnight = QtWidgets.QRadioButton(self.group_class)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_DeathKnight.setFont(font)
        self.radioButton_DeathKnight.setObjectName("radioButton_DeathKnight")
        self.gridLayout_2.addWidget(self.radioButton_DeathKnight, 3, 1, 1, 1)
        self.radioButton_Druid.raise_()
        self.radioButton_Hunter.raise_()
        self.radioButton_Mage.raise_()
        self.radioButton_Priest.raise_()
        self.radioButton_Shaman.raise_()
        self.radioButton_Rogue.raise_()
        self.radioButton_Paladin.raise_()
        self.radioButton_Paladin.raise_()
        self.radioButton_Warlock.raise_()
        self.radioButton_Warrior.raise_()
        self.radioButton_Monk.raise_()
        self.radioButton_DeathKnight.raise_()
        self.verticalLayout.addWidget(self.group_class)
        self.line = QtWidgets.QFrame(DialogCreateDeck)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.group_mode = QtWidgets.QGroupBox(DialogCreateDeck)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.group_mode.setFont(font)
        self.group_mode.setObjectName("group_mode")
        self.gridLayout = QtWidgets.QGridLayout(self.group_mode)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_standard = QtWidgets.QRadioButton(self.group_mode)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_standard.setFont(font)
        self.radioButton_standard.setChecked(True)
        self.radioButton_standard.setObjectName("radioButton_standard")
        self.gridLayout.addWidget(self.radioButton_standard, 0, 0, 1, 1)
        self.radioButton_wild = QtWidgets.QRadioButton(self.group_mode)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_wild.setFont(font)
        self.radioButton_wild.setObjectName("radioButton_wild")
        self.gridLayout.addWidget(self.radioButton_wild, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.group_mode)
        self.line_2 = QtWidgets.QFrame(DialogCreateDeck)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_deck_name = QtWidgets.QLabel(DialogCreateDeck)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_deck_name.setFont(font)
        self.label_deck_name.setObjectName("label_deck_name")
        self.horizontalLayout.addWidget(self.label_deck_name, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.edit_deck_name = QtWidgets.QLineEdit(DialogCreateDeck)
        self.edit_deck_name.setObjectName("edit_deck_name")
        self.horizontalLayout.addWidget(self.edit_deck_name, 0, QtCore.Qt.AlignTop)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogCreateDeck)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox, 0, QtCore.Qt.AlignBottom)

        self.retranslateUi(DialogCreateDeck)
        self.buttonBox.accepted.connect(DialogCreateDeck.accept)
        self.buttonBox.rejected.connect(DialogCreateDeck.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogCreateDeck)

    def retranslateUi(self, DialogCreateDeck):
        _translate = QtCore.QCoreApplication.translate
        DialogCreateDeck.setWindowTitle(_translate("DialogCreateDeck", "新建套牌"))
        self.group_class.setTitle(_translate("DialogCreateDeck", "选择职业"))
        self.radioButton_Druid.setText(_translate("DialogCreateDeck", "德鲁伊"))
        self.radioButton_Hunter.setText(_translate("DialogCreateDeck", "猎人"))
        self.radioButton_Mage.setText(_translate("DialogCreateDeck", "法师"))
        self.radioButton_Priest.setText(_translate("DialogCreateDeck", "牧师"))
        self.radioButton_Shaman.setText(_translate("DialogCreateDeck", "萨满祭司"))
        self.radioButton_Rogue.setText(_translate("DialogCreateDeck", "潜行者"))
        self.radioButton_Paladin.setText(_translate("DialogCreateDeck", "圣骑士"))
        self.radioButton_Warlock.setText(_translate("DialogCreateDeck", "术士"))
        self.radioButton_Warrior.setText(_translate("DialogCreateDeck", "战士"))
        self.radioButton_Monk.setText(_translate("DialogCreateDeck", "武僧"))
        self.radioButton_DeathKnight.setText(_translate("DialogCreateDeck", "死亡骑士"))
        self.group_mode.setTitle(_translate("DialogCreateDeck", "选择模式"))
        self.radioButton_standard.setText(_translate("DialogCreateDeck", "标准模式"))
        self.radioButton_wild.setText(_translate("DialogCreateDeck", "狂野模式"))
        self.label_deck_name.setText(_translate("DialogCreateDeck", "套牌名称"))

