# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_app.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainApp(object):
    def setupUi(self, MainApp):
        MainApp.setObjectName("MainApp")
        MainApp.resize(1175, 683)
        MainApp.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainApp)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.main_layout = QtWidgets.QGridLayout()
        self.main_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.main_layout.setContentsMargins(0, -1, 0, -1)
        self.main_layout.setHorizontalSpacing(7)
        self.main_layout.setObjectName("main_layout")
        self.main_tab = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_tab.sizePolicy().hasHeightForWidth())
        self.main_tab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.main_tab.setFont(font)
        self.main_tab.setTabPosition(QtWidgets.QTabWidget.North)
        self.main_tab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.main_tab.setElideMode(QtCore.Qt.ElideNone)
        self.main_tab.setObjectName("main_tab")
        self.tab_main = QtWidgets.QWidget()
        self.tab_main.setObjectName("tab_main")
        self.main_tab.addTab(self.tab_main, "")
        self.tab_collection = QtWidgets.QWidget()
        self.tab_collection.setObjectName("tab_collection")
        self.main_tab.addTab(self.tab_collection, "")
        self.tab_play = QtWidgets.QWidget()
        self.tab_play.setObjectName("tab_play")
        self.main_tab.addTab(self.tab_play, "")
        self.tab_adventure = QtWidgets.QWidget()
        self.tab_adventure.setObjectName("tab_adventure")
        self.main_tab.addTab(self.tab_adventure, "")
        self.tab_arena = QtWidgets.QWidget()
        self.tab_arena.setObjectName("tab_arena")
        self.main_tab.addTab(self.tab_arena, "")
        self.tab_brawl = QtWidgets.QWidget()
        self.tab_brawl.setObjectName("tab_brawl")
        self.main_tab.addTab(self.tab_brawl, "")
        self.tab_quest = QtWidgets.QWidget()
        self.tab_quest.setObjectName("tab_quest")
        self.main_tab.addTab(self.tab_quest, "")
        self.tab_open_packs = QtWidgets.QWidget()
        self.tab_open_packs.setObjectName("tab_open_packs")
        self.main_tab.addTab(self.tab_open_packs, "")
        self.tab_shop = QtWidgets.QWidget()
        self.tab_shop.setObjectName("tab_shop")
        self.main_tab.addTab(self.tab_shop, "")
        self.main_layout.addWidget(self.main_tab, 0, 0, 1, 1)
        self.gridLayout_9.addLayout(self.main_layout, 0, 0, 1, 1)
        MainApp.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainApp)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainApp.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1175, 25))
        self.menubar.setMouseTracking(False)
        self.menubar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.menubar.setObjectName("menubar")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        self.menu_game = QtWidgets.QMenu(self.menubar)
        self.menu_game.setObjectName("menu_game")
        self.menu_card = QtWidgets.QMenu(self.menubar)
        self.menu_card.setObjectName("menu_card")
        MainApp.setMenuBar(self.menubar)
        self.action_about = QtWidgets.QAction(MainApp)
        self.action_about.setShortcut("")
        self.action_about.setObjectName("action_about")
        self.action_exit = QtWidgets.QAction(MainApp)
        self.action_exit.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.action_exit.setObjectName("action_exit")
        self.action_play = QtWidgets.QAction(MainApp)
        self.action_play.setObjectName("action_play")
        self.action_adventure = QtWidgets.QAction(MainApp)
        self.action_adventure.setObjectName("action_adventure")
        self.action_arena = QtWidgets.QAction(MainApp)
        self.action_arena.setObjectName("action_arena")
        self.action_brawl = QtWidgets.QAction(MainApp)
        self.action_brawl.setObjectName("action_brawl")
        self.action_shop = QtWidgets.QAction(MainApp)
        self.action_shop.setObjectName("action_shop")
        self.action_collection = QtWidgets.QAction(MainApp)
        self.action_collection.setObjectName("action_collection")
        self.action_open_packs = QtWidgets.QAction(MainApp)
        self.action_open_packs.setObjectName("action_open_packs")
        self.action_introduction = QtWidgets.QAction(MainApp)
        self.action_introduction.setObjectName("action_introduction")
        self.action_quest = QtWidgets.QAction(MainApp)
        self.action_quest.setObjectName("action_quest")
        self.menu_help.addAction(self.action_introduction)
        self.menu_help.addAction(self.action_about)
        self.menu_game.addAction(self.action_play)
        self.menu_game.addAction(self.action_adventure)
        self.menu_game.addAction(self.action_arena)
        self.menu_game.addAction(self.action_brawl)
        self.menu_game.addSeparator()
        self.menu_game.addAction(self.action_quest)
        self.menu_game.addSeparator()
        self.menu_game.addAction(self.action_exit)
        self.menu_card.addAction(self.action_collection)
        self.menu_card.addAction(self.action_open_packs)
        self.menu_card.addSeparator()
        self.menu_card.addAction(self.action_shop)
        self.menubar.addAction(self.menu_game.menuAction())
        self.menubar.addAction(self.menu_card.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainApp)
        self.main_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainApp)

    def retranslateUi(self, MainApp):
        _translate = QtCore.QCoreApplication.translate
        MainApp.setWindowTitle(_translate("MainApp", "炉石传说"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_main), _translate("MainApp", "主页"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_collection), _translate("MainApp", "我的收藏"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_play), _translate("MainApp", "对战模式"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_adventure), _translate("MainApp", "冒险模式"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_arena), _translate("MainApp", "竞技场"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_brawl), _translate("MainApp", "乱斗模式"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_quest), _translate("MainApp", "我的任务"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_open_packs), _translate("MainApp", "打开卡包"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_shop), _translate("MainApp", "商店"))
        self.menu_help.setTitle(_translate("MainApp", "帮助(&H)"))
        self.menu_game.setTitle(_translate("MainApp", "游戏(&G)"))
        self.menu_card.setTitle(_translate("MainApp", "卡牌(&C)"))
        self.action_about.setText(_translate("MainApp", "关于(&A)..."))
        self.action_about.setIconText(_translate("MainApp", "关于"))
        self.action_about.setToolTip(_translate("MainApp", "关于(A)"))
        self.action_about.setStatusTip(_translate("MainApp", "显示关于本游戏的信息"))
        self.action_exit.setText(_translate("MainApp", "退出(&X)"))
        self.action_exit.setToolTip(_translate("MainApp", "退出(X)"))
        self.action_exit.setStatusTip(_translate("MainApp", "退出游戏"))
        self.action_play.setText(_translate("MainApp", "对战模式(&P)"))
        self.action_play.setStatusTip(_translate("MainApp", "进入对战模式"))
        self.action_adventure.setText(_translate("MainApp", "冒险模式(&A)"))
        self.action_adventure.setToolTip(_translate("MainApp", "冒险模式(A)"))
        self.action_adventure.setStatusTip(_translate("MainApp", "进入冒险模式"))
        self.action_arena.setText(_translate("MainApp", "竞技场(&R)"))
        self.action_arena.setToolTip(_translate("MainApp", "竞技场(R)"))
        self.action_arena.setStatusTip(_translate("MainApp", "进入竞技场"))
        self.action_brawl.setText(_translate("MainApp", "乱斗模式(&B)"))
        self.action_brawl.setToolTip(_translate("MainApp", "乱斗模式(B)"))
        self.action_brawl.setStatusTip(_translate("MainApp", "进入乱斗模式"))
        self.action_shop.setText(_translate("MainApp", "商店(&S)"))
        self.action_shop.setToolTip(_translate("MainApp", "商店(S)"))
        self.action_shop.setStatusTip(_translate("MainApp", "购买商品"))
        self.action_collection.setText(_translate("MainApp", "我的收藏(&C)"))
        self.action_collection.setToolTip(_translate("MainApp", "我的收藏(C)"))
        self.action_collection.setStatusTip(_translate("MainApp", "浏览我的收藏"))
        self.action_open_packs.setText(_translate("MainApp", "打开卡包(&O)"))
        self.action_open_packs.setToolTip(_translate("MainApp", "打开卡包(O)"))
        self.action_open_packs.setStatusTip(_translate("MainApp", "打开获得的卡包"))
        self.action_introduction.setText(_translate("MainApp", "游戏介绍(&I)"))
        self.action_introduction.setToolTip(_translate("MainApp", "游戏介绍(I)"))
        self.action_quest.setText(_translate("MainApp", "我的任务(&Q)"))
        self.action_quest.setToolTip(_translate("MainApp", "我的任务(Q)"))

