# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_app.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainApp(object):
    def setupUi(self, MainApp):
        MainApp.setObjectName("MainApp")
        MainApp.resize(1135, 686)
        MainApp.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainApp)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tab_main = QtWidgets.QStackedWidget(self.centralwidget)
        self.tab_main.setObjectName("tab_main")
        self.page_main = QtWidgets.QWidget()
        self.page_main.setObjectName("page_main")
        self.main_layout = QtWidgets.QGridLayout(self.page_main)
        self.main_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.main_layout.setContentsMargins(1, 0, 1, 0)
        self.main_layout.setHorizontalSpacing(7)
        self.main_layout.setObjectName("main_layout")
        self.main_tab = QtWidgets.QTabWidget(self.page_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_tab.sizePolicy().hasHeightForWidth())
        self.main_tab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.main_tab.setFont(font)
        self.main_tab.setTabPosition(QtWidgets.QTabWidget.North)
        self.main_tab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.main_tab.setElideMode(QtCore.Qt.ElideNone)
        self.main_tab.setObjectName("main_tab")
        self.tab_welcome = QtWidgets.QWidget()
        self.tab_welcome.setObjectName("tab_welcome")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_welcome)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(self.tab_welcome)
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_welcome = QtWidgets.QLabel(self.tab_welcome)
        self.label_welcome.setObjectName("label_welcome")
        self.gridLayout.addWidget(self.label_welcome, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.main_tab.addTab(self.tab_welcome, "")
        self.tab_collection = QtWidgets.QWidget()
        self.tab_collection.setObjectName("tab_collection")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_collection)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_collections_title = QtWidgets.QLabel(self.tab_collection)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_collections_title.setFont(font)
        self.label_collections_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_collections_title.setObjectName("label_collections_title")
        self.verticalLayout_4.addWidget(self.label_collections_title, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_deck = QtWidgets.QStackedWidget(self.tab_collection)
        self.widget_deck.setMaximumSize(QtCore.QSize(270, 16777215))
        self.widget_deck.setObjectName("widget_deck")
        self.page_deck_list = QtWidgets.QWidget()
        self.page_deck_list.setObjectName("page_deck_list")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.page_deck_list)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.list_decks = QtWidgets.QListWidget(self.page_deck_list)
        self.list_decks.setMaximumSize(QtCore.QSize(270, 16777215))
        self.list_decks.setObjectName("list_decks")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.list_decks.addItem(item)
        self.horizontalLayout_2.addWidget(self.list_decks)
        self.widget_deck.addWidget(self.page_deck_list)
        self.page_deck_edit = QtWidgets.QWidget()
        self.page_deck_edit.setObjectName("page_deck_edit")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_deck_edit)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.table_deck = QtWidgets.QTableWidget(self.page_deck_edit)
        self.table_deck.setMaximumSize(QtCore.QSize(270, 16777215))
        self.table_deck.setObjectName("table_deck")
        self.table_deck.setColumnCount(3)
        self.table_deck.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_deck.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_deck.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_deck.setHorizontalHeaderItem(2, item)
        self.table_deck.horizontalHeader().setCascadingSectionResizes(False)
        self.table_deck.horizontalHeader().setStretchLastSection(False)
        self.table_deck.verticalHeader().setVisible(False)
        self.verticalLayout_5.addWidget(self.table_deck)
        self.button_deck_done = QtWidgets.QPushButton(self.page_deck_edit)
        self.button_deck_done.setMaximumSize(QtCore.QSize(270, 16777215))
        self.button_deck_done.setObjectName("button_deck_done")
        self.verticalLayout_5.addWidget(self.button_deck_done)
        self.widget_deck.addWidget(self.page_deck_edit)
        self.horizontalLayout_6.addWidget(self.widget_deck)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_collection)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_collection)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 1, 3, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_collection)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 0, 3, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_collection)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_3.addWidget(self.pushButton_6, 0, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_collection)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_3.addWidget(self.pushButton_7, 1, 2, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_collection)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_3.addWidget(self.pushButton_5, 0, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_collection)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_3.addWidget(self.pushButton_8, 0, 1, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_collection)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_3.addWidget(self.pushButton_9, 1, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_3)
        self.pushButton = QtWidgets.QPushButton(self.tab_collection)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_6.addWidget(self.pushButton, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.main_tab.addTab(self.tab_collection, "")
        self.tab_play = QtWidgets.QWidget()
        self.tab_play.setObjectName("tab_play")
        self.main_tab.addTab(self.tab_play, "")
        self.tab_adventure = QtWidgets.QWidget()
        self.tab_adventure.setObjectName("tab_adventure")
        self.main_tab.addTab(self.tab_adventure, "")
        self.tab_arena = QtWidgets.QWidget()
        self.tab_arena.setObjectName("tab_arena")
        self.main_tab.addTab(self.tab_arena, "")
        self.tab_brawl = QtWidgets.QWidget()
        self.tab_brawl.setObjectName("tab_brawl")
        self.main_tab.addTab(self.tab_brawl, "")
        self.tab_quest = QtWidgets.QWidget()
        self.tab_quest.setObjectName("tab_quest")
        self.main_tab.addTab(self.tab_quest, "")
        self.tab_open_packs = QtWidgets.QWidget()
        self.tab_open_packs.setObjectName("tab_open_packs")
        self.main_tab.addTab(self.tab_open_packs, "")
        self.tab_shop = QtWidgets.QWidget()
        self.tab_shop.setObjectName("tab_shop")
        self.main_tab.addTab(self.tab_shop, "")
        self.tab_settings = QtWidgets.QWidget()
        self.tab_settings.setObjectName("tab_settings")
        self.label_settings_title = QtWidgets.QLabel(self.tab_settings)
        self.label_settings_title.setGeometry(QtCore.QRect(11, 11, 172, 84))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_settings_title.setFont(font)
        self.label_settings_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_settings_title.setObjectName("label_settings_title")
        self.layoutWidget = QtWidgets.QWidget(self.tab_settings)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 170, 298, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_change_nickname = QtWidgets.QLabel(self.layoutWidget)
        self.label_change_nickname.setObjectName("label_change_nickname")
        self.horizontalLayout.addWidget(self.label_change_nickname)
        self.edit_change_nickname = QtWidgets.QLineEdit(self.layoutWidget)
        self.edit_change_nickname.setObjectName("edit_change_nickname")
        self.horizontalLayout.addWidget(self.edit_change_nickname)
        self.button_change_nickname = QtWidgets.QPushButton(self.layoutWidget)
        self.button_change_nickname.setObjectName("button_change_nickname")
        self.horizontalLayout.addWidget(self.button_change_nickname)
        self.main_tab.addTab(self.tab_settings, "")
        self.main_layout.addWidget(self.main_tab, 0, 0, 1, 1)
        self.tab_main.addWidget(self.page_main)
        self.page_game = QtWidgets.QWidget()
        self.page_game.setObjectName("page_game")
        self.tab_main.addWidget(self.page_game)
        self.gridLayout_9.addWidget(self.tab_main, 0, 0, 1, 1)
        MainApp.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainApp)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainApp.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1135, 25))
        self.menubar.setMouseTracking(False)
        self.menubar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.menubar.setObjectName("menubar")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        self.menu_game = QtWidgets.QMenu(self.menubar)
        self.menu_game.setObjectName("menu_game")
        self.menu_card = QtWidgets.QMenu(self.menubar)
        self.menu_card.setObjectName("menu_card")
        MainApp.setMenuBar(self.menubar)
        self.action_about = QtWidgets.QAction(MainApp)
        self.action_about.setShortcut("")
        self.action_about.setObjectName("action_about")
        self.action_exit = QtWidgets.QAction(MainApp)
        self.action_exit.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.action_exit.setObjectName("action_exit")
        self.action_play = QtWidgets.QAction(MainApp)
        self.action_play.setObjectName("action_play")
        self.action_adventure = QtWidgets.QAction(MainApp)
        self.action_adventure.setObjectName("action_adventure")
        self.action_arena = QtWidgets.QAction(MainApp)
        self.action_arena.setObjectName("action_arena")
        self.action_brawl = QtWidgets.QAction(MainApp)
        self.action_brawl.setObjectName("action_brawl")
        self.action_shop = QtWidgets.QAction(MainApp)
        self.action_shop.setObjectName("action_shop")
        self.action_collection = QtWidgets.QAction(MainApp)
        self.action_collection.setObjectName("action_collection")
        self.action_open_packs = QtWidgets.QAction(MainApp)
        self.action_open_packs.setObjectName("action_open_packs")
        self.action_introduction = QtWidgets.QAction(MainApp)
        self.action_introduction.setObjectName("action_introduction")
        self.action_quest = QtWidgets.QAction(MainApp)
        self.action_quest.setObjectName("action_quest")
        self.action_settings = QtWidgets.QAction(MainApp)
        self.action_settings.setObjectName("action_settings")
        self.menu_help.addAction(self.action_introduction)
        self.menu_help.addAction(self.action_about)
        self.menu_game.addAction(self.action_play)
        self.menu_game.addAction(self.action_adventure)
        self.menu_game.addAction(self.action_arena)
        self.menu_game.addAction(self.action_brawl)
        self.menu_game.addSeparator()
        self.menu_game.addAction(self.action_quest)
        self.menu_game.addSeparator()
        self.menu_game.addAction(self.action_settings)
        self.menu_game.addAction(self.action_exit)
        self.menu_card.addAction(self.action_collection)
        self.menu_card.addAction(self.action_open_packs)
        self.menu_card.addSeparator()
        self.menu_card.addAction(self.action_shop)
        self.menubar.addAction(self.menu_game.menuAction())
        self.menubar.addAction(self.menu_card.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainApp)
        self.main_tab.setCurrentIndex(0)
        self.widget_deck.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainApp)

    def retranslateUi(self, MainApp):
        _translate = QtCore.QCoreApplication.translate
        MainApp.setWindowTitle(_translate("MainApp", "炉石传说"))
        self.label_title.setText(_translate("MainApp", "炉 石 传 说"))
        self.label_welcome.setText(_translate("MainApp", "欢迎回来！"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_welcome), _translate("MainApp", "主页"))
        self.label_collections_title.setText(_translate("MainApp", "我的收藏"))
        __sortingEnabled = self.list_decks.isSortingEnabled()
        self.list_decks.setSortingEnabled(False)
        item = self.list_decks.item(0)
        item.setText(_translate("MainApp", "新建套牌"))
        item.setStatusTip(_translate("MainApp", "新建一副套牌"))
        self.list_decks.setSortingEnabled(__sortingEnabled)
        item = self.table_deck.horizontalHeaderItem(0)
        item.setText(_translate("MainApp", "法力"))
        item = self.table_deck.horizontalHeaderItem(1)
        item.setText(_translate("MainApp", "卡牌"))
        item = self.table_deck.horizontalHeaderItem(2)
        item.setText(_translate("MainApp", "数量"))
        self.button_deck_done.setText(_translate("MainApp", "完成"))
        self.pushButton_4.setText(_translate("MainApp", "PushButton"))
        self.pushButton_2.setText(_translate("MainApp", "PushButton"))
        self.pushButton_3.setText(_translate("MainApp", "PushButton"))
        self.pushButton_6.setText(_translate("MainApp", "PushButton"))
        self.pushButton_7.setText(_translate("MainApp", "PushButton"))
        self.pushButton_5.setText(_translate("MainApp", "DSDSdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsd"))
        self.pushButton_8.setText(_translate("MainApp", "PushButton"))
        self.pushButton_9.setText(_translate("MainApp", "PushButton"))
        self.pushButton.setText(_translate("MainApp", "PushButton"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_collection), _translate("MainApp", "我的收藏"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_play), _translate("MainApp", "对战模式"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_adventure), _translate("MainApp", "冒险模式"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_arena), _translate("MainApp", "竞技场"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_brawl), _translate("MainApp", "乱斗模式"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_quest), _translate("MainApp", "我的任务"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_open_packs), _translate("MainApp", "打开卡包"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_shop), _translate("MainApp", "商店"))
        self.label_settings_title.setText(_translate("MainApp", "游戏设置"))
        self.label_change_nickname.setText(_translate("MainApp", "修改昵称"))
        self.button_change_nickname.setText(_translate("MainApp", "确定"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_settings), _translate("MainApp", "设置"))
        self.menu_help.setTitle(_translate("MainApp", "帮助(&H)"))
        self.menu_game.setTitle(_translate("MainApp", "游戏(&G)"))
        self.menu_card.setTitle(_translate("MainApp", "卡牌(&C)"))
        self.action_about.setText(_translate("MainApp", "关于(&A)..."))
        self.action_about.setIconText(_translate("MainApp", "关于"))
        self.action_about.setToolTip(_translate("MainApp", "关于(A)"))
        self.action_about.setStatusTip(_translate("MainApp", "显示关于本游戏的信息"))
        self.action_exit.setText(_translate("MainApp", "退出(&X)"))
        self.action_exit.setToolTip(_translate("MainApp", "退出(X)"))
        self.action_exit.setStatusTip(_translate("MainApp", "退出游戏"))
        self.action_play.setText(_translate("MainApp", "对战模式(&P)"))
        self.action_play.setStatusTip(_translate("MainApp", "进入对战模式"))
        self.action_adventure.setText(_translate("MainApp", "冒险模式(&A)"))
        self.action_adventure.setToolTip(_translate("MainApp", "冒险模式(A)"))
        self.action_adventure.setStatusTip(_translate("MainApp", "进入冒险模式"))
        self.action_arena.setText(_translate("MainApp", "竞技场(&R)"))
        self.action_arena.setToolTip(_translate("MainApp", "竞技场(R)"))
        self.action_arena.setStatusTip(_translate("MainApp", "进入竞技场"))
        self.action_brawl.setText(_translate("MainApp", "乱斗模式(&B)"))
        self.action_brawl.setToolTip(_translate("MainApp", "乱斗模式(B)"))
        self.action_brawl.setStatusTip(_translate("MainApp", "进入乱斗模式"))
        self.action_shop.setText(_translate("MainApp", "商店(&S)"))
        self.action_shop.setToolTip(_translate("MainApp", "商店(S)"))
        self.action_shop.setStatusTip(_translate("MainApp", "购买商品"))
        self.action_collection.setText(_translate("MainApp", "我的收藏(&C)"))
        self.action_collection.setToolTip(_translate("MainApp", "我的收藏(C)"))
        self.action_collection.setStatusTip(_translate("MainApp", "浏览我的收藏"))
        self.action_open_packs.setText(_translate("MainApp", "打开卡包(&O)"))
        self.action_open_packs.setToolTip(_translate("MainApp", "打开卡包(O)"))
        self.action_open_packs.setStatusTip(_translate("MainApp", "打开获得的卡包"))
        self.action_introduction.setText(_translate("MainApp", "游戏介绍(&I)"))
        self.action_introduction.setToolTip(_translate("MainApp", "游戏介绍(I)"))
        self.action_quest.setText(_translate("MainApp", "我的任务(&Q)"))
        self.action_quest.setToolTip(_translate("MainApp", "我的任务(Q)"))
        self.action_settings.setText(_translate("MainApp", "设置(&S)"))
        self.action_settings.setToolTip(_translate("MainApp", "设置(S)"))

