#! /usr/bin/python
# -*- coding: utf-8 -*-

"""Some basic card creators."""

from functools import partial

from .utils import create_card, add_to_module
from ...game.card import Minion, Weapon
from ...game.events import standard as std_events
from ...game.triggers import standard as std_triggers
from ...utils.game import Zone

__author__ = 'fyabc'


# Blank card creation.

def create_blank(data, name=None, card_type=Minion, module_dict=None):
    """Create a blank card (without special skills).

    Typical Usage:
        1. Give module's global dict.
        2. Or called in module's GLOBAL, without `module_dict` param.

    :param data: Card data.
    :type data: dict
    :param name: Card name, will be generated by system if not given.
    :type name: str
    :param card_type: Card type.
    :param module_dict:
        The global dict of the module.
        The result card class will be added into this dict automatically.
        If not given, will be the global dict of the CALLER.
    :type module_dict: dict
    :return: The created card class.
    """

    result = create_card(data, name, card_type)

    add_to_module(result, module_dict)

    return result


blank_minion = partial(create_blank, card_type=Minion)
blank_weapon = partial(create_blank, card_type=Weapon)


# Cards with some basic skills.

def draw_card_fn(n=1):
    """Get the draw card function.

    :param n: Number of cards.
    :type n: int
    :return: Draw card function, used as `run` or `battlecry`.
    """
    def run_battlecry(self, target, **kwargs):
        return [std_events.DrawCard(self.game, self, self.player_id)
                for _ in range(n)]
    return run_battlecry


def damage_fn(value):
    """Get the damage function.

    :param value: Damage value.
    :type value: int
    :return: Damage function, used as `run` or `battlecry`.
    """
    def run_battlecry(self, target, **kwargs):
        return [std_events.Damage(self.game, self, target, value)]
    return run_battlecry


def summon_fn(summon_id, relative_loc=1):
    """Get the summon function.

    :param summon_id: The summoned minion id.
    :type summon_id: int
    :param relative_loc: The relative location of the summoned minion.
        +1 means summon in the right of the original minion.
        0 means summon in the left of the original minion.
    :type relative_loc: int
    :return: Summon function, used as `run` or `battlecry`.
    """

    def run_battlecry(self, target, **kwargs):
        derivative_id = summon_id
        game = self.game
        loc = relative_loc + game.get_zone(Zone.Play, self.player_id).index(self)
        return std_events.pure_summon_events(
            game, minion=derivative_id, to_player=self.player_id, loc=loc,
            from_player=None, from_zone=None)
    return run_battlecry


def create_damage_entity(data, value, name=None, card_type=Minion, module_dict=None):
    result = create_card(data, name, card_type, cls_dict_others={
        'run_battlecry': damage_fn(value),
    })

    add_to_module(result, module_dict)

    return result


create_damage_minion = partial(create_damage_entity, card_type=Minion)
create_damage_weapon = partial(create_damage_entity, card_type=Weapon)


def create_summon_minion(data, summon_id, relative_loc, name=None, module_dict=None):
    result = create_card(data, name, Minion, cls_dict_others={
        'run_battlecry': summon_fn(summon_id, relative_loc),
    })

    add_to_module(result, module_dict)

    return result


# TODO: Add the commonly used deathrattle summon function.


__all__ = [
    'create_blank',
    'blank_minion',
    'blank_weapon',

    'draw_card_fn',
    'damage_fn',
    'summon_fn',
    'create_damage_entity',
    'create_damage_minion',
    'create_damage_weapon',
    'create_summon_minion',
]
