# -*- coding: utf-8 -*-

__author__ = 'fyabc'

from pygame.colordict import THECOLORS as AllColors

SCREEN_SIZE = (840, 540)
BG_COLOR = AllColors['white']
NEST_COLOR = AllColors['lightgreen']
TEXT_COLOR = AllColors['blue']

TIME_PASSED = 25

NEST_LOC = (680, 450)
NEST_RADIUS = 100

# Ant configs.
RANDOM_DESTINATION_PROB = 20
RANDOM_DROP_PROB = 10

SPIDER_ATTACKED_PROB = 7

SEE_LEAF_RANGE = 130.
SEE_SPIDER_RANGE = 150.
ATTACK_SPIDER_RANGE = 10.
CARRY_RANGE = 5.

EXPLORING_SPEED_RANGE = (90, 110)
SEEKING_SPEED_RANGE = (120, 140)
DELIVERING_SPEED_RANGE = (50, 70)
HUNTING_SPEED_RANGE = (165, 185)

SPIDER_SPEED_RANGE = (50, 90)
SPIDER_ATTACKED_SPEED_RANGE = (165, 185)

ANT_NUMBER = 10
INIT_LEAF_NUMBER = 2

LEAF_OCCUR_RANGE = 1.5

SPIDER_FREQ = 40
LEAF_FREQ = 60
CLEAR_FREQ = 800
